# Generated by Django 5.0.1 on 2024-01-20 15:22

import datetime
import psihologiy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=30)),
                ('number', models.IntegerField(default=psihologiy.models.generate_card_number_humo)),
                ('expire', models.DateField(default=datetime.datetime(2028, 1, 19, 20, 22, 32, 469163))),
                ('sms_notification_number', models.IntegerField(default=998991030904)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassportInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('tugilgan_sana', models.DateField()),
                ('passport_raqami', models.CharField(max_length=20)),
                ('berilgan_sana', models.DateField()),
                ('amal_qilish_muddati', models.DateField()),
                ('tugilgan_joyi', models.CharField(max_length=255)),
                ('manzil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_ish_beruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numer', models.FloatField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_ish_oluvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=35)),
                ('number', models.IntegerField(default=psihologiy.models.generate_card_number_uzcard)),
                ('expire', models.DateField(default=datetime.datetime(2028, 1, 19, 20, 22, 32, 468164))),
                ('sms_notification_number', models.IntegerField(default=998991030904)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
