# Generated by Django 5.0.1 on 2024-01-20 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psihologiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humo',
            name='expire',
            field=models.DateField(default=datetime.datetime(2028, 1, 19, 20, 25, 22, 181637)),
        ),
        migrations.AlterField(
            model_name='uzcard',
            name='expire',
            field=models.DateField(default=datetime.datetime(2028, 1, 19, 20, 25, 22, 180638)),
        ),
    ]
